### ISSUE TITLE
Authorization key?

### ISSUE THREAD

**Issue by maxlinux2000** [andrehtissot/cordova-plugin-firebase-extended-notification-app-example#1]
Hi,
I can build the app, and now they show me the firebase token.

but wen I try to send the demo message from notify.php 

below  the result, but no push message arrive to my phone.
I suspect that I put the wrong "authorization key on notify.php.  Could you please tell me exactly were is the autorization key in the firebase console?
A screenshot (censored) will be welcome :)

```
fields:Array
(
    [to] => 
    [data] => Array
        (
            [notificationOptions] => Array
                (
                    [text] => Test message
                    [title] => Title test
                    [smallIcon] => mipmap/icon
                    [largeIcon] => https://avatars2.githubusercontent.com/u/1174345?v=3&s=96
                    [vibrate] => 1
                    [sound] => 1
                    [autoCancel] => 1
                    [priority] => high
                )

        )

)


headers:Array
(
    [0] => Authorization:key=AIzablablablablablablablablablablablabla
    [1] => Content-Type:application/json
)


result:
```

**Comment by andrehtissot** [comment]
What I noticed is that you didn't set the "to" parameter (step 8) with the phone firebase token (step 7).
For the server key, I created this wiki entry https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example/wiki/How-to-find-your-firebase-server-key

**Comment by maxlinux2000** [comment]
Perfect!! :)

now is working!  tnx!!
