### ISSUE TITLE
Custom option

### ISSUE THREAD

**Issue by januarsy** [andrehtissot/cordova-plugin-firebase-extended-notification-app-example#2]
How to set : 
1. custom sound (alarm sound or etc..)
2. message sent to more than one registration token
3. click_action (go to another page)

thanks.. : D

**Comment by andrehtissot** [comment]
Hi  januarsy,

1.Custom sounds are accepted now, test it and tell me if it does what you need:
  * To play the default sound, use `true`;
  * To play a sound from resource, start with `res://`. For example `res://raw/music_mp3` will play the `R.raw.music_mp3` if available.
  * To play a sound from the web, start with `http://` or `https://`. For example `http://tindeck.com/download/pro/yjuow/Not_That_Guy.mp3` will download the file in cache and play it.

2.The targets are chosen as defined in `https://firebase.google.com/docs/cloud-messaging/android/send-multiple`.
It's useful to know that the plugin [cordova-plugin-fcm](https://github.com/andrehtissot/cordova-plugin-fcm), which this one is dependent, subscribes all users to the topic `all`, all the android users to the topic `android`, and all the ios users to the topic `ios`.

3.For this `click_action`, you can use the methods from [cordova-plugin-fcm](https://github.com/andrehtissot/cordova-plugin-fcm):
```javascript
FCMPlugin.onNotification(function(data){
    if(data.wasTapped){
      //Notification was received on device tray and tapped by the user.
      alert( JSON.stringify(data) );
    }else{
      //Notification was received in foreground. Maybe the user needs to be notified.
      alert( JSON.stringify(data) );
    }
});
```

**Comment by januarsy** [comment]
Thank you for your help.

I've tried setting it, but it did not manage to make a sound, what should I do with this script.

```
<?php

$fields = array(
	'to' => '...',
  	'data' => array(
    	'notificationOptions' => array(
		'text' => 'Test message',
		'title' => 'Title test',
		'smallIcon' => 'fcm_push_icon',
		'vibrate' => true,

		'sound' => 'http://asg.angkasapura1.co.id/mysound.mp3',  // Not Working
 or		'sound' => 'res://raw/mysound', // Not Working

		'click_action' => 'FCM_PLUGIN_ACTIVITY',
		'autoCancel' => true,
		'priority' => 'high'
    	)
  	)
);

$headers = array(
  'Authorization:key=...',
  'Content-Type:application/json'
);

......
.....
```

**Comment by andrehtissot** [comment]
I couldn't find the error, even with your source.

Are you sure you updated the plugin?

Can you send me the log (`adb logcat`) from the time you starts the app to the time it should/do show the notification?

Sent to andrehtissot@gmail.com if you prefer to not attach here.

And another thing: You shouldn't share your server key. With this key, anyone can send messages to all the devices connected easily.

**Comment by andrehtissot** [comment]
I've tested with the `google-services.json` that you sent me and the server key that was in this issue post and got this message in the server as result:

```php
result:Array
(
    [multicast_id] => 6959974632748107390
    [success] => 0
    [failure] => 1
    [canonical_ids] => 0
    [results] => Array
        (
            [0] => Array
                (
                    [error] => MismatchSenderId
                )

        )
)
```


Than I used my own testing `google-services.json` and server key and it just worked.

Look at the array result you are getting, if it is like mine "MismatchSenderId", means that you should check your `google-services.json` and server key.

[Tutorial here](https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example/wiki/How-to-find-your-firebase-server-key)
