### ISSUE TITLE
Send message to all users

### ISSUE THREAD

**Issue by bugis** [andrehtissot/cordova-plugin-firebase-extended-notification-app-example#4]
Hi..
How send message to targeted user segment (without enter all users token).

**Comment by andrehtissot** [comment]
Hi bugis,

By default:
- All android users will receive messages from topic `android`;
- All ios users will receive messages from topic `ios`;
- All users will receive messages from topic `all`;

What you need to do is change the value of the `to` parameter to `/topics/all`.

To know more about topics, [look here](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging).
